pipeline {
    agent any
    stages {
		stage('Clone') {
            steps {
                bat "git clone https://github.com/brajesh9718/springbootwithswaggeruiapprepo.git"
            }
        }
        stage('Build') {
            steps {
                bat "mvn clean install -f swagger/pom.xml"
            }
        }
        stage('Test'){
        	steps {
        		bat "mvn test -f swagger/"
        	}
        }
        stage('Package'){
        	steps {
        		bat "mvn package -f swagger/"
        	}
        }
        stage('Deploy') {
            steps {
            	echo "Deploying........"
                bat 'copy "C:\\Program Files (x86)\\Jenkins\\workspace\\cicd-pipeline-stages\\cicdpipelineapp\\target\\"  "C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\"' 
            }
        }
        
    }
}
